### PR TITLE
Add Verbose Option

### PR DESCRIPTION
**Pull request by ghost**
I add a option -v (or --verbose) to let the tester print verbose statements, such as:
Started new process (someId) at time t (someTime) 
Process (someId) request a new rate of (someRate) at t (someTime)
Ended process (someId) after (someLifetime) ticks at time t (someTime)

### CODE REVIEW

**Comment by andrewbuss** [comment]
Looks good. I suggest rebasing to clean up the merge commits though.

**Comment by brandonio21** [comment]
Thanks a ton. I will test this no later than 10:30 PST

**Comment by brandonio21** [comment]
Also, this can not be properly merged due to conflicts. Think you can either rebase or apply new commits on top of yours? Thanks!

**Comment by ghost** [comment]
Ok. I will work on that !

**Comment by ghost** [comment]
Done !

**Comment by brandonio21** [comment]
Works great. Merging.

**Comment by ghost** [comment]
Sorry... I just found out a simple calculation error...

**Pull request merged**
