### PR TITLE
Restore validation of equal scheduling of leftover processes

### PR DESCRIPTION
**Pull request by andrewbuss**
This got broken on the last PR.

### CODE REVIEW

**Comment by ghost** [comment]
Hi Andrew,
For leftover validation:
count = processes[i].tick_count;
if process A and B starts at different time, they should have different tick count right?

**Comment by andrewbuss** [comment]
No, we reset the tick counts of leftover processes whenever a process starts, or if a leftover process ends. So leftover processes should have tick counts within 1 of each other

**Comment by andrewbuss** [comment]
No, we reset the tick counts of leftover processes whenever a process starts, or if a leftover process ends. So leftover processes should have tick counts within 1 of each other

**Comment by andrewbuss** [comment]
No, we reset the tick counts of leftover processes whenever a process starts, or if a leftover process ends. So leftover processes should have tick counts within 1 of each other

**Comment by ghost** [comment]
Oh I see. Thanks!

**Pull request merged**
