### PR TITLE
add all binary combinations of test_havoc for extra stressfulness

### PR DESCRIPTION
**Pull request by metakirby5**

### CODE REVIEW

**Comment by brandonio21** [comment]
This PR is a little over the top, don't you think? :wink:

**Comment by metakirby5** [comment]
:smirk: :fire: :computer:

**Comment by brandonio21** [comment]
Put this functionality into an additional flag, and I'll merge. Something like "--break-ieng9"  

No seriously just put it under "--stress" or something. The goal is to provide the user quick and easy feedback by default. If they want to, they can initiate this.

**Comment by andrewbuss** [comment]
This is a bit much IMO, and I'm usually a fan of exhaustive tests. 1 million ticks for each introduces a not-insignificant runtime, and these combinations don't introduce terribly much testing variety. I'd be perfectly okay with this if they only ran for 10000 ticks each though

**Comment by brandonio21** [comment]
You're right, @andrewbuss. Let's also turn down the ticks.

**Comment by metakirby5** [comment]
don't worry, i wasn't serious - the additions are pretty trivial so it shouldn't really be included :stuck_out_tongue:

**Pull request closed without merging**
