### PR TITLE
Check if all procs are exited & fix RR

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by brandonio21** [comment]
Looks good. Do you think we could add in a Printf on the failures describing that a failure occurred because we tried to schedule an ended process? I just don't want the user to be blind.

**Comment by ghost** [comment]
Sure I will add that as well.

**Comment by ghost** [comment]
I added fix for RR as well.

**Comment by brandonio21** [comment]
This looks great. Thanks so much!

**Pull request merged**
